# -*- coding: utf-8 -*-
"""ML_HW1_Q2_400243092_RashinRahnamoun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRr7UwPbEG5Gi39B1-L1-l-BHR89VnW1
"""

!wget --no-check-certificate "https://drive.google.com/uc?export=download&id=1m99MN7VSPxsxduYM6FVO_9wWxgOtqgy_" -O adult.data

import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

import pandas as pd

new_columns = [
    "Age",
    "Employment_Sector",
    "Census_Weight",
    "Degree_Attained",
    "Years_of_Education",
    "Marital_Status",
    "Occupation",
    "Family_Relationship",
    "Race",
    "Gender",
    "Capital_Gain",
    "Investment_Losses",
    "Hours_Per_Week",
    "Native_Country",
    "Income"
]

df = pd.read_csv(
    "adult.data",
    names=new_columns,
    dtype={
        "Age": float,
        "Census_Weight": float,
        "Years_of_Education": float,
        "Capital_Gain": float,
        "Investment_Losses": float,
        "Hours_Per_Week": float
    },
    sep=",",
    engine="python",
    na_values=["?", " ", "", "NA", "NaN", "nan"]
)

print("=== First 3 Rows ===")
print(df.head(3))

print("\n=== Missing Values Report ===")
print(df.isnull().sum())

print("\n=== Data Summary ===")
print(df.describe(include='all'))

print("\n=== Categorical Value Counts ===")
categorical_cols = df.select_dtypes(include=['object']).columns
for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].value_counts(dropna=False))

print("\n=== Data Types ===")
print(df.dtypes)

print("\n=== Unique Values per Column ===")
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

numeric_cols = df.select_dtypes(include=[np.number]).columns
categorical_cols = df.select_dtypes(exclude=[np.number]).columns
df = df.drop(columns=df.columns[df.isna().mean() > 0.85])
for col in numeric_cols:
    if df[col].isna().any():
        if col in ['Capital_Gain', 'Investment_Losses']:
            df[col] = df[col].interpolate(method='polynomial', order=2)
        else:
            df[col] = df[col].fillna(df[col].median())

for col in categorical_cols:
    if df[col].isna().any():
        mode_val = df[col].mode()[0]
        df[col] = df[col].fillna(mode_val)
df.dropna(inplace=True)
print("\nMissing values after treatment:")
print(df.isna().sum())

print("\nVerification - any remaining null values:", df.isnull().values.any())
print("Total remaining null values:", df.isnull().sum().sum())

if df.isnull().values.any():
    print("\nWarning: There are still missing values in the dataset!")
    print("Columns with missing values:")
    print(df.isnull().sum()[df.isnull().sum() > 0])
else:
    print("\nSuccess: All missing values have been handled!")

plt.figure(figsize=(10, 6))
sns.set_theme(style="whitegrid")

income_plot = sns.countplot(
    x='Income', data=df,
    palette='magma_r',
    order=df['Income'].value_counts().index,
    edgecolor="black", linewidth=1.2
)

plt.title('Distribution of Income Levels', fontsize=18, fontweight='bold', pad=20)
plt.xlabel('Income Category', fontsize=14, fontweight='bold')
plt.ylabel('Number of Individuals', fontsize=14, fontweight='bold')

plt.xticks(fontsize=12)
plt.yticks(fontsize=12)

total = len(df)
for p in income_plot.patches:
    count = p.get_height()
    percentage = f'{100 * count / total:.1f}%'

    income_plot.annotate(f'{count:,}',
                         (p.get_x() + p.get_width() / 2., count),
                         ha='center', va='bottom',
                         xytext=(0, 5),
                         textcoords='offset points',
                         fontsize=12, fontweight='bold', color='black',
                         bbox=dict(facecolor='white', alpha=0.7, edgecolor='none'))

    income_plot.annotate(percentage,
                         (p.get_x() + p.get_width() / 2., count),
                         ha='center', va='top',
                         xytext=(0, -20),
                         textcoords='offset points',
                         fontsize=12, color='black')

plt.tight_layout()
plt.show()

num_fea = ['Age', 'Hours_Per_Week', 'Capital_Gain', 'Investment_Losses', 'Census_Weight','Years_of_Education']

print(df[num_fea].describe().T[['count', 'mean', 'std', 'min', '25%', '50%', '75%', 'max']])

plt.figure(figsize=(20, 15))

plt.subplot(2, 3, 1)
sns.histplot(df['Age'], bins=30, kde=True, color='#4c72b0')
plt.title('Age Distribution')

plt.subplot(2, 3, 2)
sns.histplot(df['Hours_Per_Week'], bins=30, kde=True, color='#55a868')
plt.title('Weekly Working Hours')

plt.subplot(2, 3, 3)
sns.histplot(df[df['Capital_Gain']>0]['Capital_Gain'], bins=30, kde=True, color='#c44e52', log_scale=True)
plt.title('Capital Gain (Log Scale)')

plt.subplot(2, 3, 4)
sns.histplot(df[df['Investment_Losses']>0]['Investment_Losses'], bins=30, kde=True, color='#8172b2')
plt.title('Investment Losses')

plt.subplot(2, 3, 5)
sns.histplot(df['Census_Weight'], bins=30, kde=True, color='#ccb974')
plt.title('Census Weight Distribution')

plt.subplot(2, 3, 6)
sns.histplot(df['Years_of_Education'], bins=30, kde=True, color='#64b5cd')
plt.title('Years of Education')

plt.tight_layout()
plt.savefig('all_features_distribution.png', dpi=300, bbox_inches='tight')
plt.show()

df['Income'] = df['Income'].map({'<=50K': 0, '>50K': 1})



correlation_matrix = df[num_fea].corr()

plt.figure(figsize=(14, 12))
mask = np.triu(np.ones_like(correlation_matrix, dtype=bool))
sns.heatmap(
    correlation_matrix,
    mask=mask,
    annot=True,
    fmt=".2f",
    cmap="YlOrRd",
    center=0,
    square=True,
    linewidths=0.5,
    cbar_kws={"shrink": 0.8},
    annot_kws={"size": 10}
)

plt.xticks(rotation=45, ha='right', fontsize=10)
plt.yticks(rotation=0, fontsize=10)
plt.title('Numerical Features Correlation Matrix',
         fontsize=14, pad=20, fontweight='bold')

plt.tight_layout()
plt.savefig('correlation_matrix.png', dpi=300, bbox_inches='tight', transparent=True)
plt.show()

#features_to_remove = ['Census_Weight', 'Investment_Losses']
features_to_remove = ['Census_Weight']
df = df.drop(columns=features_to_remove)

print("Removed features:", features_to_remove)
print("Remaining features:", df.columns.tolist())

categorical_features = [col for col in df.columns
                       if col not in num_fea + ['Income']]

df = pd.get_dummies(
    df,
    columns=categorical_features,
    prefix=categorical_features,
    drop_first=True
)

"""**Q2_b**"""

import numpy as np
from collections import Counter
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

class KNNClassifier:
    def __init__(self, neighbors=3):
        self._neighbors = neighbors
        self._features = None
        self._labels = None
        self._classes = None

    def fit(self, X, y):
        self._features = np.array(X, dtype=float)
        self._labels = np.array(y)
        self._classes = np.unique(y)
        return self

    def predict(self, X):
        if self._features is None or self._labels is None:
            raise ValueError("Model must be fitted before prediction")
        X = np.array(X, dtype=float)
        return np.array([self._predict_single(sample) for sample in X])

    def predict_proba(self, X):
        if self._features is None or self._labels is None:
            raise ValueError("Model must be fitted before prediction")
        X = np.array(X, dtype=float)
        return np.array([self._predict_proba_single(sample) for sample in X])

    def evaluate(self, X_test, y_test):
        y_pred = self.predict(X_test)
        return self._calculate_metrics(y_test, y_pred)

    def _predict_single(self, sample):
        sample = np.asarray(sample, dtype=float)
        distances = np.linalg.norm(self._features - sample, axis=1)
        nearest_indices = np.argpartition(distances, self._neighbors)[:self._neighbors]
        nearest_labels = self._labels[nearest_indices]
        return Counter(nearest_labels).most_common(1)[0][0]

    def _predict_proba_single(self, sample):
        sample = np.asarray(sample, dtype=float)
        distances = np.linalg.norm(self._features - sample, axis=1)
        nearest_indices = np.argpartition(distances, self._neighbors)[:self._neighbors]
        nearest_labels = self._labels[nearest_indices]
        counts = Counter(nearest_labels)
        return np.array([counts.get(cls, 0) / self._neighbors for cls in self._classes])

    def _calculate_metrics(self, y_true, y_pred):
        accuracy = accuracy_score(y_true, y_pred)
        precision = precision_score(y_true, y_pred, average="weighted", zero_division=0)
        recall = recall_score(y_true, y_pred, average="weighted", zero_division=0)
        f1 = f1_score(y_true, y_pred, average="weighted", zero_division=0)

        return {
            "accuracy": accuracy,
            "precision": precision,
            "recall": recall,
            "f1_score": f1
        }

    @property
    def neighbors(self):
        return self._neighbors

    @neighbors.setter
    def neighbors(self, value):
        if not isinstance(value, int) or value <= 0:
            raise ValueError("Number of neighbors must be a positive integer")
        self._neighbors = value

    @property
    def classes(self):
        return self._classes

    def __repr__(self):
        return f"KNNClassifier(neighbors={self._neighbors})"

"""**Q2_c**"""

X = df.drop('Income', axis=1).values
y = df['Income'].values

def train_test_split(X, y, test_size=0.3, random_state=None):
    if random_state: np.random.seed(random_state)
    indices = np.arange(X.shape[0])
    np.random.shuffle(indices)
    split_idx = int(X.shape[0] * (1 - test_size))
    return X[indices[:split_idx]], X[indices[split_idx:]], y[indices[:split_idx]], y[indices[split_idx:]]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=29)

knn = KNNClassifier(neighbors=5)
knn.fit(X_train, y_train)

predictions = knn.predict(X_test)
metrics = knn.evaluate(y_test, predictions)

print(f"Accuracy: {metrics['accuracy']:.2f}")
print(f"Precision: {metrics['precision']:.2f}")
print(f"Recall: {metrics['recall']:.2f}")
print(f"F1: {metrics['f1_score']:.2f}")

"""**Q2_d**"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, accuracy_score, f1_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

knn = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred):.2f}")
print(f"Precision: {precision_score(y_test, y_pred):.2f}")
print(f"Recall: {recall_score(y_test, y_pred):.2f}")
print(f"F1 Score: {f1_score(y_test, y_pred):.2f}")

"""**Q2_e**"""

import logging
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV, RandomizedSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from time import time
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger()

class KNNOptimizer:
    def __init__(self, X, y):
        self.X = X
        self.y = y
        self.X_train, self.X_test, self.y_train, self.y_test = train_test_split(X, y, test_size=0.3, random_state=42)
        self.best_model = None

    def grid_search(self):
        p_grid = {
            'n_neighbors': range(1, 51,5),
            'p': [1, 2]
        }
        gs = GridSearchCV(
            KNeighborsClassifier(algorithm='brute', metric='minkowski'),
            p_grid,
            cv=5,
            scoring='accuracy',
            n_jobs=6
        )
        logger.info("Starting GridSearchCV...")
        gs.fit(self.X_train, self.y_train)
        logger.info("GridSearchCV completed!")
        logger.info(f"Best Parameters: {gs.best_params_}")
        logger.info(f"Best Score: {gs.best_score_}")
        print(gs.best_params_)
        print(gs.best_score_)
        self.best_model = gs.best_estimator_
        return gs.best_params_, gs.best_score_

    def random_search(self):
        p_dist = {
            'n_neighbors': np.arange(1, 51),
            'p': [1, 2],

        }
        rs = RandomizedSearchCV(
            KNeighborsClassifier(algorithm='brute', metric='minkowski'),
            p_dist,
            n_iter=20,
            cv=5,
            scoring='accuracy',
            random_state=19,
            n_jobs=6
        )
        logger.info("Starting RandomizedSearchCV...")
        rs.fit(self.X_train, self.y_train)
        logger.info("RandomizedSearchCV completed!")
        logger.info(f"Best Parameters: {rs.best_params_}")
        logger.info(f"Best Score: {rs.best_score_}")
        print(rs.best_params_)
        print(rs.best_score_)
        self.best_model = rs.best_estimator_
        return rs.best_params_, rs.best_score_

    def evaluate_model(self):
        if self.best_model is None:
            raise ValueError("No model trained yet. Run grid_search() or random_search() first.")

        y_pred = self.best_model.predict(self.X_test)

        logger.info("Classification Report:")
        logger.info(classification_report(self.y_test, y_pred))

        cm = confusion_matrix(self.y_test, y_pred)
        plt.figure(figsize=(6, 4))
        sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
        plt.title('Confusion Matrix')
        plt.xlabel('Predicted')
        plt.ylabel('Actual')
        plt.show()




opt = KNNOptimizer(X, y)
best_params, best_score = opt.grid_search()
print(best_params, best_score)
opt.evaluate_model()
best_params, best_score = opt.random_search()
print(best_params, best_score)

"""**Q2_f**"""

def compare_algorithms(X_tr, X_te, y_tr):
    results = []

    for alg in ['ball_tree', 'kd_tree', 'brute']:
        knn = KNeighborsClassifier(n_neighbors=5, algorithm=alg, metric='minkowski')

        start = time.time()
        knn.fit(X_tr, y_tr)
        y_pr = knn.predict(X_te)
        total_time = time.time() - start

        print(f"{alg}: {total_time:.4f} seconds")

        results.append({
            'Algorithm': alg,
            'Time (s)': total_time
        })

    df = pd.DataFrame(results)

    plt.figure(figsize=(8, 5))
    sns.barplot(x='Algorithm', y='Time (s)', data=df)
    plt.title('Algorithm Time Comparison')
    plt.show()

    return df

timing = compare_algorithms(X_tr, X_te, y_tr)