# -*- coding: utf-8 -*-
"""ML_HW1_Q1_400243092_RashinRahnamoun.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O1U_rD5MY5KIp2dtJFOkBhaaIDXq3Stz
"""

!pip install numpy pandas

!gdown --id 1XWlztTX-K9OMIVcVHTUTX-q6SVj-oHFN

"""**Q1_a**"""

import pandas as pd
import numpy as np

df = pd.read_csv('loan_data.csv')

print("Dataset Overview:")
print(df.info())
print("\nTop 5 Entries:")
print(df.head())
print("\nStatistical Summary:")
print(df.describe())
print("\nMissing Data Count:")
print(df.isnull().sum())
print("\nList of Columns:")
print(df.columns)
print("\nDistinct Values in Each Column:")
for col in df.columns:
    print(f"{col}: {df[col].nunique()} unique values")

#df = pd.read_csv('loan_data.csv')

for col in df.columns:
    if df[col].dtype in ['int64', 'float64']:
        df[col].fillna(df[col].mean(), inplace=True)
    else:
        df[col].fillna(df[col].mode()[0], inplace=True)

print("\nRemaining Missing Data:")
print(df.isnull().sum())

cat = df.select_dtypes(include=['object', 'category']).columns
for col in cat:
    uni = df[col].unique()
    val_map = {v: i for i, v in enumerate(uni)}
    df[col] = df[col].map(val_map)

print("\nData After Categorical Encoding:")
print(df.head())

X = df.iloc[:, :-1]
X_min = X.min()
X_max = X.max()
X_nrm = (X - X_min) / (X_max - X_min)

print("\nData After Normalization:")
print(X_nrm.head())

X_mean = X.mean()
X_std = X.std()
X_stdzd = (X - X_mean) / X_std

print("\nData After Standardization:")
print(X_stdzd.head())

X_f = X_stdzd
y_f = df.iloc[:, -1]

"""**Q1_b**"""

import numpy as np
import pandas as pd
from collections import Counter

class DecisionTree:
    def __init__(self, max_depth=None, min_samples_split=2):
        self.md = max_depth
        self.ms = min_samples_split
        self.tr = None

    def calculate_entropy(self, y):
        class_counts = Counter(y)
        entropy = 0
        total_instances = len(y)
        for count in class_counts.values():
            probability = count / total_instances
            entropy -= probability * np.log2(probability)
        return entropy

    def calculate_gini(self, y):
        class_counts = Counter(y)
        probability = [count / len(y) for count in class_counts.values()]
        return 1 - np.sum(np.array(probability) ** 2)

    def information_gain(self, X, y, feature, criterion='entropy'):
        pc = self.calculate_entropy(y) if criterion == 'entropy' else self.calculate_gini(y)
        val, cnt = np.unique(X[:, feature], return_counts=True)
        wa = np.sum([
            (cnt[i] / np.sum(cnt)) * (self.calculate_entropy(y[X[:, feature] == val[i]]) if criterion == 'entropy' else self.calculate_gini(y[X[:, feature] == val[i]]))
            for i in range(len(val))
        ])
        return pc - wa

    def best_split(self, X, y):
        bf, bg = None, -1
        for f in range(X.shape[1]):
            g = self.information_gain(X, y, f)
            if g > bg:
                bg, bf = g, f
        return bf

    def build_tree(self, X, y, depth=0):
        if len(np.unique(y)) == 1 or len(y) < self.ms or (self.md and depth >= self.md):
            return np.argmax(np.bincount(y))

        f = self.best_split(X, y)
        if f is None:
            return np.argmax(np.bincount(y))

        tr = {f: {}}
        for v in np.unique(X[:, f]):
            sX, sY = X[X[:, f] == v], y[X[:, f] == v]
            tr[f][v] = self.build_tree(sX, sY, depth + 1)
        return tr

    def predict(self, X):
      def traverse(tree, instance):
          if not isinstance(tree, dict):
              return tree
          feature = list(tree.keys())[0]
          value = instance[feature]
          subtree = tree[feature].get(value, Counter(self.y_train).most_common(1)[0][0])
          return traverse(subtree, instance)

      return np.array([traverse(self.tr, x) for x in X])

    def fit(self, X, y):
        self.tr = self.build_tree(X, y)
        self.y_train = y



    def evaluate(self, y_true, y_pred):
        tp, tn, fp, fn = np.sum((y_true == 1) & (y_pred == 1)), np.sum((y_true == 0) & (y_pred == 0)), np.sum((y_true == 0) & (y_pred == 1)), np.sum((y_true == 1) & (y_pred == 0))
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

        return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

"""**Q1_c**"""

def train_test_split(X, y, test_size=0.2):
    n = len(X)
    test_set_size = int(n * test_size)
    indices = np.random.permutation(n)
    X_train, X_test = X.iloc[indices[:-test_set_size]], X.iloc[indices[-test_set_size:]]
    y_train, y_test = y.iloc[indices[:-test_set_size]], y.iloc[indices[-test_set_size:]]
    return X_train, X_test, y_train, y_test

X_train, X_test, y_train, y_test = train_test_split(X_f, y_f, test_size=0.2)

dt = DecisionTree(max_depth=100, min_samples_split=2)
dt.fit(X_train.to_numpy(), y_train.to_numpy())
y_pred = dt.predict(X_test.to_numpy())

results = dt.evaluate(y_test.to_numpy(), y_pred)
print(results)

"""**Q1_c2**"""

import numpy as np
import pandas as pd
from collections import Counter

class DecisionTree:
    def __init__(self, max_depth=None, min_samples_split=2):
        self.md = max_depth
        self.ms = min_samples_split
        self.tr = None
        self.majority_class = None

    def calculate_entropy(self, y):
        class_counts = Counter(y)
        entropy = 0
        total_instances = len(y)
        for count in class_counts.values():
            probability = count / total_instances
            entropy -= probability * np.log2(probability)
        return entropy

    def calculate_gini(self, y):
        class_counts = Counter(y)
        probability = [count / len(y) for count in class_counts.values()]
        return 1 - np.sum(np.array(probability) ** 2)

    def information_gain(self, X, y, feature, criterion='entropy'):
        pc = self.calculate_entropy(y) if criterion == 'entropy' else self.calculate_gini(y)
        val, cnt = np.unique(X[:, feature], return_counts=True)
        wa = np.sum([
            (cnt[i] / np.sum(cnt)) * (self.calculate_entropy(y[X[:, feature] == val[i]]) if criterion == 'entropy' else self.calculate_gini(y[X[:, feature] == val[i]]))
            for i in range(len(val))
        ])
        return pc - wa

    def best_split(self, X, y):
        bf, bg = None, -1
        for f in range(X.shape[1]):
            g = self.information_gain(X, y, f)
            if g > bg:
                bg, bf = g, f
        return bf

    def build_tree(self, X, y, depth=0):
        if len(np.unique(y)) == 1 or len(y) < self.ms or (self.md and depth >= self.md):
            return np.argmax(np.bincount(y))

        f = self.best_split(X, y)
        if f is None:
            return np.argmax(np.bincount(y))

        tr = {f: {}}
        for v in np.unique(X[:, f]):
            sX, sY = X[X[:, f] == v], y[X[:, f] == v]
            tr[f][v] = self.build_tree(sX, sY, depth + 1)
        return tr

    def predict(self, X):
        def traverse(tree, instance):
            if not isinstance(tree, dict):
                return tree
            feature = list(tree.keys())[0]
            value = instance[feature]
            subtree = tree[feature].get(value, self.majority_class)
            return traverse(subtree, instance)

        return np.array([traverse(self.tr, x) for x in X])

    def fit(self, X, y):
        self.tr = self.build_tree(X, y)
        self.majority_class = np.argmax(np.bincount(y))

    def evaluate(self, y_true, y_pred):
        tp, tn, fp, fn = np.sum((y_true == 1) & (y_pred == 1)), np.sum((y_true == 0) & (y_pred == 0)), np.sum((y_true == 0) & (y_pred == 1)), np.sum((y_true == 1) & (y_pred == 0))
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

        return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

#df = pd.read_csv('loan_data.csv')
df = pd.get_dummies(df, drop_first=True)
X = df.drop('loan_status', axis=1).values
y = df['loan_status'].values
train_size = int(0.8 * len(X))
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]
dt = DecisionTree(max_depth=15, min_samples_split=2)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
evaluation_results = dt.evaluate(y_test, y_pred)
print(evaluation_results)

import numpy as np
import pandas as pd
from collections import Counter


class DecisionTree:
    def __init__(self, max_depth=None, min_samples_split=2, criterion='entropy'):
        self.md = max_depth
        self.ms = min_samples_split
        self.cr = criterion
        self.tr = None
        self.mc = None

    def calculate_entropy(self, y):
        cc = Counter(y)
        t = len(y)
        return -sum((c/t) * np.log2(c/t) for c in cc.values())

    def calculate_gini(self, y):
        cc = Counter(y)
        t = len(y)
        return 1 - sum((c/t)**2 for c in cc.values())

    def _get_split_gain(self, p, yl, yr):
        nl, nr, nt = len(yl), len(yr), len(yl) + len(yr)
        if self.cr == 'entropy':
            g = p - (nl/nt * self.calculate_entropy(yl) + nr/nt * self.calculate_entropy(yr))
        else:
            g = p - (nl/nt * self.calculate_gini(yl) + nr/nt * self.calculate_gini(yr))
        return g

    def _best_split(self, xc, y):
        u = np.unique(xc)
        if len(u) < 2:
            return (None, None)
        p = self.calculate_entropy(y) if self.cr == 'entropy' else self.calculate_gini(y)
        if len(u) > 10:
            si = np.argsort(xc)
            sx, sy = xc[si], y[si]
            sp = (u[:-1] + u[1:]) / 2
            bg = -float('inf')
            bs = None
            for s in sp:
                li = np.searchsorted(sx, s, side='left')
                yl, yr = sy[:li], sy[li:]
                if len(yl) == 0 or len(yr) == 0:
                    continue
                g = self._get_split_gain(p, yl, yr)
                if g > bg:
                    bg = g
                    bs = s
        else:
            bg = p
            bs = None
            for v in u:
                sb = y[xc == v]
                g = p - (len(sb)/len(y) * (self.calculate_entropy(sb) if self.cr == 'entropy' else self.calculate_gini(sb)))
                if g > bg:
                    bg = g
                    bs = v
        return (bs, bg)

    def best_split(self, X, y):
      bf, bg, bs, bn = None, -float('inf'), None, False
      for f in range(X.shape[1]):
          sv, g = self._best_split(X[:, f], y)
          if g is not None and g > bg:
              bg, bf, bs, bn = g, f, sv, len(np.unique(X[:, f])) > 10
      return (bf, bs, bn)


    def build_tree(self, X, y, d=0):
        if len(np.unique(y)) == 1 or (self.md is not None and d >= self.md) or (len(y) < self.ms):
            return np.argmax(np.bincount(y))
        f, sv, bn = self.best_split(X, y)
        if f is None:
            return np.argmax(np.bincount(y))
        n = {'feature': f, 'split_val': sv, 'is_numerical': bn}
        if bn:
            lm = X[:, f] <= sv
            rm = ~lm
            n['left'] = self.build_tree(X[lm], y[lm], d+1)
            n['right'] = self.build_tree(X[rm], y[rm], d+1)
        else:
            n['children'] = {}
            for v in np.unique(X[:, f]):
                m = X[:, f] == v
                n['children'][v] = self.build_tree(X[m], y[m], d+1)
        return n

    def predict(self, X):
        def _traverse(n, x):
            if isinstance(n, np.int64):
                return n
            if n['is_numerical']:
                return _traverse(n['left'], x) if x[n['feature']] <= n['split_val'] else _traverse(n['right'], x)
            return _traverse(n['children'].get(x[n['feature']], self.mc), x)
        return np.array([_traverse(self.tr, x) for x in X])

    def fit(self, X, y):
        self.tr = self.build_tree(X, y)
        self.mc = np.argmax(np.bincount(y))


    def evaluate(self, y_true, y_pred):
        tp, tn, fp, fn = np.sum((y_true == 1) & (y_pred == 1)), np.sum((y_true == 0) & (y_pred == 0)), np.sum((y_true == 0) & (y_pred == 1)), np.sum((y_true == 1) & (y_pred == 0))
        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0
        f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0

        return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

X = df.drop('loan_status', axis=1).values
y = df['loan_status'].values
train_size = int(0.8 * len(X))
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]
dt = DecisionTree(max_depth=15, min_samples_split=2, criterion='gini')
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
evaluation_results = dt.evaluate(y_test, y_pred)
print(evaluation_results)

"""**Q1_d**"""

import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

def evaluate(y_true, y_pred):
    tp, tn, fp, fn = np.sum((y_true == 1) & (y_pred == 1)), np.sum((y_true == 0) & (y_pred == 0)), np.sum((y_true == 0) & (y_pred == 1)), np.sum((y_true == 1) & (y_pred == 0))
    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    accuracy = (tp + tn) / (tp + tn + fp + fn) if (tp + tn + fp + fn) > 0 else 0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0
    return {"accuracy": accuracy, "precision": precision, "recall": recall, "f1": f1}

train_size = int(0.8 * len(X))
X_train, X_test = X[:train_size], X[train_size:]
y_train, y_test = y[:train_size], y[train_size:]

sklearn_dt = DecisionTreeClassifier(max_depth=15, min_samples_split=2, random_state=42)
sklearn_dt.fit(X_train, y_train)
sklearn_pred = sklearn_dt.predict(X_test)

results = evaluate(y_test, sklearn_pred)
print(results)